---
title: "Reflections on Bias-Variance Trade-off"
description: "Reflections on bias-variance trade-off."
date: 2023-10-15
categories: [Modeling, Machine-Learning]
---

## Introduction
I studied bias-variance trade-off six years ago for the first time. Since then I have accumulated a lot more knowledge about machine learning and the field as a 
whole has genuinely progressed quite a bit. In this piece, I will be reflecting on how bias-variance trade-off appears in ML modeling.

## What is Bias-Variance trade-off?
The main idea behind ML you are given some data generating function and your objective is to learn some aspect of the data it produces. Some examples are:


|Task | Data Generating Function | Aspect of Data (objective) |
| ----------------- | -------------------------| ---------------------------|
| Classify an email into spam                | Emails                   | Whether it's a spam or not                                     | 
| Cluster customers into various segments    | Customer activity        | Insights into customer purchasing activity                     |
| Simulate a user activity on platform       | User activity            | Regeneration of user activity to apply to new product surfaces | 

In all of the above cases, the function generating the underlying data is quite complex and covers many aspects of it. For example, email generation 
activity depends on your profession, personality, writing style etc. There are no universal laws such as our beloved Newton's laws of motion that we can fall back
to explain the how emails are generated. All we can do is look at some emails, see which ones are spam and not, try to extract the pattern out of it, and
hope it generalizes to the emails we have not seen yet. This is where machine learning comes in handy.

In an ideal world, we will have infinite data, inifinite computational and time resources and models capable
of training on infinite data. In that case, we can ensure model generalizes. But since we live in a finite world, we have
to make some approximations to make learning possible. So, you first select data that you believe is a good enough 
representative of the target aspect of the data from this generating function. Then you pick an algorithm that fits 
this data well. The whole process looks like this:  
- Data selection: the selection process ensures target is well representative.  
- Model training: process of fitting a model to the selected data.   
- Model evaluation: evaluating the model to understand to what extent it generalizes to unseen data.  

*Write about how in the approximating process, some potential errors are introduced and how we calculate them*

## Mathematical definition

*Mathematically derive how bias variance trade-off work*

## Bias-Variance in Traditional ML

*Demonstrate bias-variance in traditional ML*

## Bias Variance in Neural Network

*Show affect of over parameterization and double descent*

## Bias Variance in the era of LLM

*Talk about how in LLM era, the product exploration etc has been accelerated. We now use zero-shot capabilities of model to predict and that 
we should treat not only examples as data but the information in prompt specification as data as well and giving too much of it can introduce 
variance or bias. It would be great to demonstrate this, but I am not sure how.*

## Concluding Remarks
*Will need to see how these concluding remarks come to be*







































